AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Pycon US 2024 supporting code

Resources:
  VanillaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: vanilla.handler
      CodeUri: ./function/
      Timeout: 30
      MemorySize: 256
      Description: Sample Lambda function without instrumentation - pycon us 2024

Outputs:
  VanillaFunctionArn:
    Description: ARN used for CLI testing
    Value: !Ref VanillaFunction
